# Generated by Django 5.0 on 2024-04-12 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, max_length=200, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
