# Generated by Django 5.0 on 2024-04-13 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_genre_is_sub_remove_genre_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(error_messages={'null': 'Trường này không được để trống.'}, max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Tên danh mục phải có ít nhất 6 kí tự.')]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
