# Generated by Django 5.0 on 2024-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
