# Generated by Django 5.0 on 2024-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chapter_name_alter_story_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
