# Generated by Django 5.0 on 2024-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(related_name='story_genre', to='app.genre'),
        ),
    ]
