# Generated by Django 5.0 on 2024-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrome_count', models.IntegerField(default=0)),
                ('firefox_count', models.IntegerField(default=0)),
                ('edge_count', models.IntegerField(default=0)),
                ('safari_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
            ],
        ),
    ]
