# Generated by Django 5.0 on 2024-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_browserstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
